"""Economy management: worker production, expansions, supply, production buildings."""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from sc2.ids.unit_typeid import UnitTypeId
from sc2.ids.upgrade_id import UpgradeId

from bots.cand_4280017f_a.decision_engine import StrategicState

if TYPE_CHECKING:
    from sc2.bot_ai import BotAI


# Saturation constants
WORKERS_PER_BASE_MINERALS = 16  # 2 per mineral patch, ~8 patches
WORKERS_PER_GAS = 3
MAX_WORKERS = 44

# Supply constants
SUPPLY_BUFFER = 8  # Build pylon when supply_cap - supply_used <= buffer
PYLON_SUPPLY = 8

# Production constants
GATEWAY_PER_BASE = 2
ROBO_THRESHOLD_BASES = 2

# Mineral-float gateway scaling: add gateways when floating minerals
MINERAL_FLOAT_GATEWAY_THRESHOLD = 500  # minerals above which we add gateways
MINERAL_FLOAT_GATEWAY_PER_500 = 1       # 1 extra gateway per 500 floating minerals
MAX_GATEWAYS = 12                        # hard cap to prevent overbuilding


@dataclass
class MacroDecision:
    """A single macro decision to be executed."""

    action: str  # "train", "build", "expand"
    target: str  # UnitTypeId name or expansion label
    reason: str

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dict."""
        return {"action": self.action, "target": self.target, "reason": self.reason}


class MacroManager:
    """Manages economy: worker production, expansions, supply, production buildings.

    The macro manager reads the strategic state from the decision engine and
    adjusts priorities accordingly. During 'opening', macro is handled by the
    build order. During other states, the macro manager takes over.
    """

    def __init__(self) -> None:
        self._pending: list[MacroDecision] = []

    @property
    def pending_decisions(self) -> list[MacroDecision]:
        """Decisions generated by the last evaluate() call."""
        return self._pending

    def evaluate(self, bot: BotAI, strategic_state: StrategicState) -> list[MacroDecision]:
        """Evaluate the current game state and generate macro decisions.

        Args:
            bot: The BotAI instance with current game state.
            strategic_state: Current strategic state from the decision engine.

        Returns:
            List of macro decisions to execute.
        """
        self._pending = []

        # During opening, build order handles macro
        if strategic_state == StrategicState.OPENING:
            return self._pending

        self._check_supply(bot)
        self._check_workers(bot)
        self._check_expansion(bot, strategic_state)
        self._check_production_buildings(bot)
        self._check_warp_gate_research(bot)
        self._check_forge_and_upgrades(bot)
        self._check_twilight_upgrades(bot)
        self._check_shield_batteries(bot)
        self._check_gas(bot)

        return self._pending

    def _check_supply(self, bot: BotAI) -> None:
        """Build pylons when supply is getting tight.

        Scales the supply buffer with gateway count so multi-gateway
        warp-in cycles don't get supply-blocked.
        """
        supply_left = int(bot.supply_cap) - int(bot.supply_used)
        if bot.supply_cap >= 200:
            return

        gateway_count = len(bot.structures(UnitTypeId.GATEWAY)) + len(
            bot.structures(UnitTypeId.WARPGATE)
        )
        # Each gateway warp-in needs ~2 supply; buffer enough for a full cycle
        desired_buffer = max(SUPPLY_BUFFER, gateway_count * 2)

        pending_pylons = bot.already_pending(UnitTypeId.PYLON)
        pylons_needed = int(max(
            0,
            (desired_buffer - supply_left + PYLON_SUPPLY - 1) // PYLON_SUPPLY
            - pending_pylons,
        ))
        for _ in range(min(pylons_needed, 2)):
            self._pending.append(
                MacroDecision(
                    action="build",
                    target="Pylon",
                    reason=(
                        f"Supply tight ({int(bot.supply_used)}/{int(bot.supply_cap)},"
                        f" need {desired_buffer} buffer)"
                    ),
                )
            )

    def _check_workers(self, bot: BotAI) -> None:
        """Train probes if below saturation.

        Pauses probe production when floating minerals and army supply
        is low, freeing supply headroom for gateway army production.
        """
        ideal_workers = self._ideal_worker_count(bot)
        current_workers = len(bot.units(UnitTypeId.PROBE))
        pending_workers = bot.already_pending(UnitTypeId.PROBE)

        # Pause probes when floating minerals and army is undersized,
        # so gateway production can use the supply headroom.
        minerals = int(bot.minerals)
        army_supply = int(bot.supply_used) - current_workers
        if minerals > 400 and army_supply < 20 and current_workers >= 22:
            return

        if current_workers + pending_workers < ideal_workers:
            # Train from idle nexus
            for _nexus in bot.townhalls.idle:
                if current_workers + pending_workers >= ideal_workers:
                    break
                self._pending.append(
                    MacroDecision(
                        action="train",
                        target="Probe",
                        reason=f"Workers {current_workers}/{ideal_workers}",
                    )
                )
                pending_workers += 1

    def _check_expansion(self, bot: BotAI, strategic_state: StrategicState) -> None:
        """Take a new expansion if saturated and safe."""
        base_count = len(bot.townhalls)
        current_workers = len(bot.units(UnitTypeId.PROBE))
        ideal_for_current = base_count * WORKERS_PER_BASE_MINERALS
        minerals = int(bot.minerals)

        # Anti-float override: during DEFEND, allow expansion when floating
        # severe minerals on saturated bases. Sitting on a huge bank while
        # defending is a guaranteed loss — the extra base adds supply cap
        # and new building real estate.
        if strategic_state == StrategicState.DEFEND:
            float_override = (
                minerals >= 1500
                and current_workers >= ideal_for_current - 2
                and base_count < 4
            )
            if not float_override:
                return

        # Expand when worker count is close to saturation of current bases
        if current_workers >= ideal_for_current - 2 and bot.minerals >= 400:
            pending_nexus = bot.already_pending(UnitTypeId.NEXUS)
            if pending_nexus == 0:
                reason = f"Workers near saturation ({current_workers}/{ideal_for_current})"
                if strategic_state == StrategicState.DEFEND:
                    reason = f"Anti-float expand: floating {minerals}m while defending"
                self._pending.append(
                    MacroDecision(
                        action="expand",
                        target="Nexus",
                        reason=reason,
                    )
                )

    def _check_production_buildings(self, bot: BotAI) -> None:
        """Ensure enough gateways and tech buildings."""
        base_count = len(bot.townhalls)
        gateway_count = len(bot.structures(UnitTypeId.GATEWAY)) + len(
            bot.structures(UnitTypeId.WARPGATE)
        )

        # CyberneticsCore safety net: if a Gateway is ready but no CyberCore
        # exists, build one. The build order may have silently failed to place it.
        cyber_count = len(bot.structures(UnitTypeId.CYBERNETICSCORE))
        if cyber_count == 0 and gateway_count >= 1:
            gw_structs = bot.structures(UnitTypeId.GATEWAY)
            wg_structs = bot.structures(UnitTypeId.WARPGATE)
            try:
                has_ready = bool(gw_structs.ready) or bool(wg_structs.ready)
            except AttributeError:
                has_ready = bool(gw_structs) or bool(wg_structs)
            if has_ready and bot.already_pending(UnitTypeId.CYBERNETICSCORE) == 0:
                self._pending.append(
                    MacroDecision(
                        action="build",
                        target="CyberneticsCore",
                        reason="Safety net: CyberCore missing after opening",
                    )
                )

        desired_gateways = base_count * GATEWAY_PER_BASE

        # Mineral-float scaling: if floating minerals, add more gateways
        # to convert excess income into army faster
        minerals = int(bot.minerals)
        if minerals > MINERAL_FLOAT_GATEWAY_THRESHOLD:
            extra = (minerals - MINERAL_FLOAT_GATEWAY_THRESHOLD) // 500 + 1
            desired_gateways = max(desired_gateways, gateway_count + extra)
        desired_gateways = min(desired_gateways, MAX_GATEWAYS)

        pending_gateways = bot.already_pending(UnitTypeId.GATEWAY)
        if gateway_count + pending_gateways < desired_gateways:
            self._pending.append(
                MacroDecision(
                    action="build",
                    target="Gateway",
                    reason=self._gateway_reason(
                        gateway_count, desired_gateways, minerals,
                    ),
                )
            )

        # Robotics Facility after 2 bases
        if base_count >= ROBO_THRESHOLD_BASES:
            robo_count = len(bot.structures(UnitTypeId.ROBOTICSFACILITY))
            if robo_count == 0:
                pending_robo = bot.already_pending(UnitTypeId.ROBOTICSFACILITY)
                if pending_robo == 0:
                    self._pending.append(
                        MacroDecision(
                            action="build",
                            target="RoboticsFacility",
                            reason="Unlocking Robo tech after 2nd base",
                        )
                    )

        # Twilight Council after CyberCore — unlocks Charge/Blink upgrades
        if cyber_count >= 1:
            tc_count = len(bot.structures(UnitTypeId.TWILIGHTCOUNCIL))
            if tc_count == 0 and bot.already_pending(UnitTypeId.TWILIGHTCOUNCIL) == 0:
                self._pending.append(
                    MacroDecision(
                        action="build",
                        target="TwilightCouncil",
                        reason="Unlocking Charge/Blink upgrades",
                    )
                )

        # Templar Archives after Twilight — unlocks HighTemplar / Archon path
        tc_structs = bot.structures(UnitTypeId.TWILIGHTCOUNCIL)
        try:
            has_tc_ready = bool(tc_structs.ready)
        except AttributeError:
            has_tc_ready = bool(tc_structs)
        if has_tc_ready:
            ta_count = len(bot.structures(UnitTypeId.TEMPLARARCHIVE))
            if ta_count == 0 and bot.already_pending(UnitTypeId.TEMPLARARCHIVE) == 0:
                self._pending.append(
                    MacroDecision(
                        action="build",
                        target="TemplarArchive",
                        reason="Unlocking HighTemplar / Archon splash path",
                    )
                )

        # Robotics Bay after Robo — unlocks Colossus
        robo_structs = bot.structures(UnitTypeId.ROBOTICSFACILITY)
        try:
            has_robo_ready = bool(robo_structs.ready)
        except AttributeError:
            has_robo_ready = bool(robo_structs)
        if has_robo_ready:
            rb_count = len(bot.structures(UnitTypeId.ROBOTICSBAY))
            if rb_count == 0 and bot.already_pending(UnitTypeId.ROBOTICSBAY) == 0:
                self._pending.append(
                    MacroDecision(
                        action="build",
                        target="RoboticsBay",
                        reason="Unlocking Colossus production",
                    )
                )

        # Stargate after CyberCore — unlocks air units (Void Ray, Phoenix, Carrier)
        if cyber_count >= 1 and base_count >= 3:
            sg_count = len(bot.structures(UnitTypeId.STARGATE))
            if sg_count == 0 and bot.already_pending(UnitTypeId.STARGATE) == 0:
                self._pending.append(
                    MacroDecision(
                        action="build",
                        target="Stargate",
                        reason="Unlocking air tech on 3rd base",
                    )
                )

        # Fleet Beacon after Stargate — unlocks Carrier and Tempest
        sg_structs = bot.structures(UnitTypeId.STARGATE)
        try:
            has_sg_ready = bool(sg_structs.ready)
        except AttributeError:
            has_sg_ready = bool(sg_structs)
        if has_sg_ready:
            fb_count = len(bot.structures(UnitTypeId.FLEETBEACON))
            if fb_count == 0 and bot.already_pending(UnitTypeId.FLEETBEACON) == 0:
                self._pending.append(
                    MacroDecision(
                        action="build",
                        target="FleetBeacon",
                        reason="Unlocking Carrier/Tempest production",
                    )
                )

    def _check_warp_gate_research(self, bot: BotAI) -> None:
        """Research Warp Gate at the Cybernetics Core when available."""
        try:
            if bot.already_pending_upgrade(UpgradeId.WARPGATERESEARCH) > 0:
                return
        except (TypeError, AttributeError):
            return
        cores = bot.structures(UnitTypeId.CYBERNETICSCORE).ready.idle
        if not cores:
            return
        if bot.can_afford(UpgradeId.WARPGATERESEARCH):
            self._pending.append(
                MacroDecision(
                    action="research",
                    target="WarpGateResearch",
                    reason="Unlock WarpGate for instant warp-ins",
                )
            )

    def _check_forge_and_upgrades(self, bot: BotAI) -> None:
        """Build a Forge after CyberCore is ready, then research attack/armor upgrades."""
        # Need CyberneticsCore before Forge
        cyber_structs = bot.structures(UnitTypeId.CYBERNETICSCORE)
        try:
            cyber_ready = cyber_structs.ready
        except AttributeError:
            cyber_ready = cyber_structs  # test mock returns plain list
        if not cyber_ready:
            return

        forge_structs = bot.structures(UnitTypeId.FORGE)
        if not forge_structs:
            if bot.already_pending(UnitTypeId.FORGE) == 0 and bot.can_afford(
                UnitTypeId.FORGE
            ):
                self._pending.append(
                    MacroDecision(
                        action="build",
                        target="Forge",
                        reason="Unlocking ground upgrades",
                    )
                )
            return

        # Forge exists — research upgrades (attack first, then armor)
        try:
            forges_idle = forge_structs.ready.idle
        except AttributeError:
            forges_idle = forge_structs  # test mock
        if not forges_idle:
            return

        upgrade_queue: list[UpgradeId] = [
            UpgradeId.PROTOSSGROUNDWEAPONSLEVEL1,
            UpgradeId.PROTOSSGROUNDARMORSLEVEL1,
            UpgradeId.PROTOSSGROUNDWEAPONSLEVEL2,
            UpgradeId.PROTOSSGROUNDARMORSLEVEL2,
        ]
        for upgrade in upgrade_queue:
            try:
                if bot.already_pending_upgrade(upgrade) > 0:
                    continue
            except (TypeError, AttributeError):
                continue
            if bot.can_afford(upgrade):
                self._pending.append(
                    MacroDecision(
                        action="research",
                        target=upgrade.name,
                        reason=f"Researching {upgrade.name}",
                    )
                )
                return  # One upgrade at a time

    def _check_twilight_upgrades(self, bot: BotAI) -> None:
        """Research Charge and Blink at the Twilight Council."""
        tc_structs = bot.structures(UnitTypeId.TWILIGHTCOUNCIL)
        try:
            tc_idle = tc_structs.ready.idle
        except AttributeError:
            tc_idle = tc_structs
        if not tc_idle:
            return

        upgrade_queue: list[UpgradeId] = [
            UpgradeId.CHARGE,  # Zealots close distance instantly
            UpgradeId.BLINKTECH,  # Stalkers can blink (micro)
        ]
        for upgrade in upgrade_queue:
            try:
                if bot.already_pending_upgrade(upgrade) > 0:
                    continue
            except (TypeError, AttributeError):
                continue
            if bot.can_afford(upgrade):
                self._pending.append(
                    MacroDecision(
                        action="research",
                        target=upgrade.name,
                        reason=f"Researching {upgrade.name}",
                    )
                )
                return  # One upgrade at a time

    def _check_shield_batteries(self, bot: BotAI) -> None:
        """Build 1-2 Shield Batteries near the natural for defense."""
        # Need CyberneticsCore + 2 bases
        cyber = bot.structures(UnitTypeId.CYBERNETICSCORE)
        try:
            has_cyber = bool(cyber.ready)
        except AttributeError:
            has_cyber = bool(cyber)
        if not has_cyber or len(bot.townhalls) < 2:
            return

        battery_count = len(bot.structures(UnitTypeId.SHIELDBATTERY))
        if battery_count >= 2:
            return
        pending = bot.already_pending(UnitTypeId.SHIELDBATTERY)
        if pending > 0:
            return
        if bot.can_afford(UnitTypeId.SHIELDBATTERY):
            self._pending.append(
                MacroDecision(
                    action="build",
                    target="ShieldBattery",
                    reason=f"Defensive battery ({battery_count}/2)",
                )
            )

    def _check_gas(self, bot: BotAI) -> None:
        """Build assimilators on bases that don't have them.

        Limits to 1 gas per base in the first 4 minutes to preserve
        mineral income for army production, then allows full saturation.
        """
        gas_count = len(bot.gas_buildings)
        base_count = len(bot.townhalls)

        # Limit gas early to preserve mineral income for army
        try:
            game_time = float(bot.time)
        except (TypeError, AttributeError):
            game_time = 300.0  # default: assume late enough to allow full gas
        # 1 gas per base before 3 min, then full 2 per base
        max_gas = base_count if game_time < 180 else base_count * 2
        if gas_count >= max_gas:
            return

        for nexus in bot.townhalls.ready:
            geysers = bot.vespene_geyser.closer_than(10, nexus)
            for geyser in geysers:
                if not bot.gas_buildings.closer_than(1, geyser):
                    pending_gas = bot.already_pending(UnitTypeId.ASSIMILATOR)
                    if pending_gas < 1:
                        self._pending.append(
                            MacroDecision(
                                action="build",
                                target="Assimilator",
                                reason=f"Gas needed at base near {nexus.position}",
                            )
                        )
                        return  # One at a time

    @staticmethod
    def _gateway_reason(current: int, desired: int, minerals: int) -> str:
        """Build reason string for gateway construction."""
        reason = f"Gateways {current}/{desired}"
        if minerals > MINERAL_FLOAT_GATEWAY_THRESHOLD:
            reason += f" (floating {minerals}m)"
        return reason

    @staticmethod
    def _ideal_worker_count(bot: BotAI) -> int:
        """Calculate ideal worker count based on current base count."""
        base_count = len(bot.townhalls)
        gas_count = len(bot.gas_buildings)
        ideal = base_count * WORKERS_PER_BASE_MINERALS + gas_count * WORKERS_PER_GAS
        return min(ideal, MAX_WORKERS)
