"""Army movement, kiting, focus fire, and ability usage."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from sc2.ids.unit_typeid import UnitTypeId

# Priority targeting: higher = kill first
TARGET_PRIORITY: dict[UnitTypeId, int] = {
    # High-value support units
    UnitTypeId.MEDIVAC: 10,
    UnitTypeId.SENTRY: 9,
    UnitTypeId.WARPPRISM: 9,
    UnitTypeId.INFESTOR: 9,
    UnitTypeId.VIPER: 9,
    UnitTypeId.QUEEN: 8,
    # Siege / splash units
    UnitTypeId.SIEGETANKSIEGED: 8,
    UnitTypeId.SIEGETANK: 7,
    UnitTypeId.COLOSSUS: 8,
    UnitTypeId.DISRUPTOR: 8,
    UnitTypeId.HIGHTEMPLAR: 9,
    # Core army
    UnitTypeId.STALKER: 5,
    UnitTypeId.MARAUDER: 5,
    UnitTypeId.ROACH: 4,
    UnitTypeId.HYDRALISK: 6,
    UnitTypeId.MUTALISK: 7,
    # Low priority
    UnitTypeId.MARINE: 3,
    UnitTypeId.ZERGLING: 2,
    UnitTypeId.ZEALOT: 3,
    # Workers
    UnitTypeId.SCV: 1,
    UnitTypeId.PROBE: 1,
    UnitTypeId.DRONE: 1,
}

DEFAULT_PRIORITY = 3

# Kiting: units that should kite (ranged units with enough range)
KITING_UNITS = {
    UnitTypeId.STALKER,
    UnitTypeId.SENTRY,
    UnitTypeId.IMMORTAL,
    UnitTypeId.COLOSSUS,
    UnitTypeId.VOIDRAY,
}

# Safe kiting distance — stay this far from melee enemies
KITE_DISTANCE = 5.0


@dataclass
class MicroCommand:
    """A single micro-level command for a unit."""

    unit_tag: int
    action: str  # "attack", "move", "kite", "ability"
    target_tag: int | None = None
    target_position: tuple[float, float] | None = None
    ability_id: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dict."""
        d: dict[str, Any] = {"unit_tag": self.unit_tag, "action": self.action}
        if self.target_tag is not None:
            d["target_tag"] = self.target_tag
        if self.target_position is not None:
            d["target_position"] = list(self.target_position)
        if self.ability_id is not None:
            d["ability_id"] = self.ability_id
        return d


def select_target(
    enemies: list[Any],
    priorities: dict[UnitTypeId, int] | None = None,
    army_center: Any | None = None,
    max_range: float = 15.0,
) -> Any | None:
    """Select the highest-priority enemy target.

    Args:
        enemies: List of enemy Unit objects (or mocks with .type_id, .health).
        priorities: Optional custom priority map. Uses TARGET_PRIORITY if None.
        army_center: Optional center point with .x/.y to filter nearby enemies.
        max_range: Maximum distance from army_center to consider.

    Returns:
        The highest-priority enemy unit, or None if list is empty.
    """
    if not enemies:
        return None

    candidates = enemies
    if army_center is not None:
        nearby = [
            e
            for e in enemies
            if (
                (e.position.x - army_center.x) ** 2
                + (e.position.y - army_center.y) ** 2
            )
            ** 0.5
            <= max_range
        ]
        if nearby:
            candidates = nearby

    prio_map = priorities if priorities is not None else TARGET_PRIORITY

    def sort_key(unit: Any) -> tuple[int, float]:
        # Higher priority first (negate), then lowest health + shield
        priority = prio_map.get(unit.type_id, DEFAULT_PRIORITY)
        return (-priority, float(unit.health + unit.shield))

    return min(candidates, key=sort_key)


def should_kite(unit_type: UnitTypeId) -> bool:
    """Check if a unit type should use kiting micro.

    Args:
        unit_type: The UnitTypeId to check.

    Returns:
        True if the unit should kite.
    """
    return unit_type in KITING_UNITS


def kite_position(
    unit_pos: tuple[float, float],
    enemy_pos: tuple[float, float],
    distance: float = KITE_DISTANCE,
) -> tuple[float, float]:
    """Calculate a position to kite away from an enemy.

    Moves directly away from the enemy by the specified distance.

    Args:
        unit_pos: Current position of our unit (x, y).
        enemy_pos: Position of the nearest enemy (x, y).
        distance: How far to move away.

    Returns:
        Target position (x, y) to move to.
    """
    dx = unit_pos[0] - enemy_pos[0]
    dy = unit_pos[1] - enemy_pos[1]

    # Distance between positions
    dist = (dx * dx + dy * dy) ** 0.5

    if dist == 0:
        # On top of each other, move in arbitrary direction
        return (unit_pos[0] + distance, unit_pos[1])

    # Normalize and scale
    nx = dx / dist * distance
    ny = dy / dist * distance

    return (unit_pos[0] + nx, unit_pos[1] + ny)


class MicroController:
    """Manages unit-level combat micro."""

    def __init__(self) -> None:
        self._commands: list[MicroCommand] = []

    @property
    def commands(self) -> list[MicroCommand]:
        """Commands generated by the last evaluate() call."""
        return self._commands

    def generate_commands(
        self,
        own_units: list[Any],
        enemy_units: list[Any],
        rally_point: tuple[float, float] | None = None,
    ) -> list[MicroCommand]:
        """Generate micro commands for all combat units.

        Args:
            own_units: List of our combat units.
            enemy_units: List of visible enemy units.
            rally_point: Optional rally point for units with no nearby enemies.

        Returns:
            List of MicroCommand instances.
        """
        self._commands = []

        if not own_units:
            return self._commands

        # Compute army centroid for proximity-filtered targeting
        avg_x = sum(u.position.x for u in own_units) / len(own_units)
        avg_y = sum(u.position.y for u in own_units) / len(own_units)
        army_center = type("P", (), {"x": avg_x, "y": avg_y})()

        # Find focus target near own army
        focus_target = select_target(enemy_units, army_center=army_center)

        for unit in own_units:
            # Skip workers
            if unit.type_id in (UnitTypeId.PROBE, UnitTypeId.SCV, UnitTypeId.DRONE):
                continue

            if enemy_units:
                # Find closest enemy for kiting decisions
                closest_enemy = min(enemy_units, key=lambda e: self._dist(unit, e))
                dist_to_closest = self._dist(unit, closest_enemy)

                if should_kite(unit.type_id) and dist_to_closest < KITE_DISTANCE:
                    # Kite away from closest enemy
                    pos = kite_position(
                        (unit.position.x, unit.position.y),
                        (closest_enemy.position.x, closest_enemy.position.y),
                    )
                    self._commands.append(
                        MicroCommand(
                            unit_tag=unit.tag,
                            action="kite",
                            target_position=pos,
                        )
                    )
                elif focus_target is not None:
                    # Attack the focus target
                    self._commands.append(
                        MicroCommand(
                            unit_tag=unit.tag,
                            action="attack",
                            target_tag=focus_target.tag,
                        )
                    )
            elif rally_point is not None:
                # No enemies visible, move to rally point
                self._commands.append(
                    MicroCommand(
                        unit_tag=unit.tag,
                        action="move",
                        target_position=rally_point,
                    )
                )

        return self._commands

    @staticmethod
    def _dist(a: Any, b: Any) -> float:
        """Euclidean distance between two units."""
        dx = a.position.x - b.position.x
        dy = a.position.y - b.position.y
        return float((dx * dx + dy * dy) ** 0.5)
